# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0006_auto_20160715_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('regdt', models.DateTimeField(auto_now_add=True, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_writer', to='member.Member')),
            ],
            options={
                'db_table': 'tbl_comment',
            },
        ),
    ]
