# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='tbl_board',
        ),
    ]
