# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20160707_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
