# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member'),
        ('board', '0005_auto_20160711_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='member_id',
        ),
        migrations.AddField(
            model_name='board',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
