# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='moddt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='member',
            name='regdt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
