# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20160708_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
