# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 05:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0003_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('moddt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('regdt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'tbl_member',
            },
        ),
    ]
