# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user_id',
            new_name='user',
        ),
    ]
